### ISSUE TITLE
Ledger device: CLA_NOT_SUPPORTED (0x6e00)

### ISSUE THREAD

**Issue by qiluge** [CryptoAeon/zil-ledger-js-interface#2]
simple code:
```
const TransportNodeHid = require("@ledgerhq/hw-transport-node-hid").default;
const Zil = require("./index").default;

let getAddr = async () => {
    const t = await TransportNodeHid.create();
    const zil = new Zil(t);
    const pubKey = await zil.getPublicKey(0);
    const address = await zil.getPublicAddress(0);
    console.log("pubkey %s, addr %s", pubKey, address);
};

getAddr().catch(e => {
    console.log(e)
});
```

result is:
```
{ Error
    at new TransportStatusError (G:\工作\zilliqa\ledger-test\node_modules\@ledgerhq\errors\src\index.js:308:16)
    at TransportNodeHid.Transport.send (G:\工作\zilliqa\ledger-test\node_modules\@ledgerhq\hw-transport\src\Transport.js:211:13)
  name: 'TransportStatusError',
  message: 'Ledger device: CLA_NOT_SUPPORTED (0x6e00)',
  stack:
   'Error\n    at new TransportStatusError (G:\\工作\\zilliqa\\ledger-test\\node_modules\\@ledgerhq\\errors\\src\\index.js:308:16)\n    at TransportNodeHid.Transport.send (G:\\工作\\zilliqa\\ledger-test\\node_modules\\@ledgerhq\\hw-transport\\src\\Transport.js:211:13)',
  statusCode: 28160,
  statusText: 'CLA_NOT_SUPPORTED' }
```

dependency:
```
{
    "@ledgerhq/hw-transport-node-hid": "^5.11.0",
    "@zilliqa-js/account": "^0.8.9",
    "@zilliqa-js/crypto": "^0.8.9",
    "@zilliqa-js/util": "^0.8.8"
  }
```

**Comment by qiluge** [comment]
My device is Ledger Nano S 
Firmware version 1.6.0

**Comment by qiluge** [comment]
solved. reinstall zil app through ledger live
